query getEvent($input: String!) {
  event(id: $input) {
    id
    name
    address
    description
    maxAttendees
    startDateTime
    status
    community {
      name
    }
    users {
      id
      name
      lastName
    }
  }
}
