import type { CodegenConfig } from "@graphql-codegen/cli";

import defaultConfig from "./graphql.config";

const noTypeCheckingPlugin = {
  add: {
    content: [
      "/* eslint-disable @typescript-eslint/ban-ts-comment */",
      "// @ts-nocheck",
      "/* eslint-disable */",
      "/* prettier-ignore */",
      "/* This file is automatically generated. Please do not modify it manually. */",
    ],
  },
};
const config = {
  ...defaultConfig,
  hooks: {
    afterOneFileWrite: ["prettier --write"],
  },
  ignoreNoDocuments: true,
  generates: {
    "app/api/gql/": {
      preset: "client",
      plugins: [noTypeCheckingPlugin],
      config: {
        useTypeImports: true,
        skipTypename: true,
        avoidOptionals: false,
        nonOptionalTypename: false,
        // Lamentablemente, code-gen establece "any" como predeterminado, cuando no tiene un
        // tipo para un "scalar". Esta opción nos obliga a definir un tipo cada vez que
        // queremos usar un escalar sin tipo.
        defaultScalarType: "unknown",
        scalars: {
          Date: "string",
          DateTime: "string",
        },
      },
    },
    "./app/api/gql/schema.gql": {
      plugins: ["schema-ast"],
    },
    "app/": {
      preset: "near-operation-file",
      presetConfig: {
        extension: ".generated.tsx",
        baseTypesPath: "api/gql/graphql.ts",
      },
      config: {
        gqlImport: "graphql-tag#gql",
      },
      plugins: [
        "typescript-operations",
        "typescript-react-apollo",
        noTypeCheckingPlugin,
      ],
    },
  },
} satisfies CodegenConfig;

export default config;
