query myTickets($input: PaginatedInputMyTicketsSearchValues!) {
  myTickets(input: $input) {
    data {
      approvalStatus
      id
      paymentStatus
      redemptionStatus
      ticketTemplate {
        id
        name
      }
      purchaseOrder {
        id
        currency {
          id
          currency
          validPaymentMethods
        }
        finalPrice
        status
      }
    }
    pagination {
      currentPage
      pageSize
      totalPages
      totalRecords
    }
  }
}
