/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* eslint-disable */
/* prettier-ignore */
/* This file is automatically generated. Please do not modify it manually. */
import * as Types from '../../../api/gql/graphql';

import { gql } from "graphql-tag";
import * as Apollo from "@apollo/client";
const defaultOptions = {} as const;
export type MyTicketsQueryVariables = Types.Exact<{
  input: Types.PaginatedInputEventsSearchInput;
  userTicketSearchInput?: Types.InputMaybe<Types.EventsTicketsSearchInput>;
}>;

export type MyTicketsQuery = {
  __typename?: "Query";
  searchEvents: {
    __typename?: "PaginatedEvent";
    data: Array<{
      __typename?: "Event";
      id: string;
      name: string;
      description?: string | null;
      startDateTime: any;
      status: Types.EventStatus;
      community?: {
        __typename?: "Community";
        id: string;
        name?: string | null;
      } | null;
      usersTickets: Array<{
        __typename?: "UserTicket";
        id: string;
        approvalStatus: Types.TicketApprovalStatus;
        paymentStatus: Types.TicketPaymentStatus;
        redemptionStatus: Types.TicketRedemptionStatus;
        ticketTemplate: {
          __typename?: "Ticket";
          description?: string | null;
          id: string;
        };
      }>;
    }>;
    pagination: {
      __typename?: "Pagination";
      currentPage: number;
      pageSize: number;
      totalPages: number;
      totalRecords: number;
    };
  };
};

export const MyTicketsDocument = gql`
  query myTickets(
    $input: PaginatedInputEventsSearchInput!
    $userTicketSearchInput: EventsTicketsSearchInput
  ) {
    searchEvents(input: $input) {
      data {
        id
        name
        description
        startDateTime
        community {
          id
          name
        }
        status
        usersTickets(input: $userTicketSearchInput) {
          id
          approvalStatus
          paymentStatus
          redemptionStatus
          ticketTemplate {
            description
            id
          }
        }
      }
      pagination {
        currentPage
        pageSize
        totalPages
        totalRecords
      }
    }
  }
`;

/**
 * __useMyTicketsQuery__
 *
 * To run a query within a React component, call `useMyTicketsQuery` and pass it any options that fit your needs.
 * When your component renders, `useMyTicketsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useMyTicketsQuery({
 *   variables: {
 *      input: // value for 'input'
 *      userTicketSearchInput: // value for 'userTicketSearchInput'
 *   },
 * });
 */
export function useMyTicketsQuery(
  baseOptions: Apollo.QueryHookOptions<
    MyTicketsQuery,
    MyTicketsQueryVariables
  > &
    (
      | { variables: MyTicketsQueryVariables; skip?: boolean }
      | { skip: boolean }
    ),
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<MyTicketsQuery, MyTicketsQueryVariables>(
    MyTicketsDocument,
    options,
  );
}
export function useMyTicketsLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    MyTicketsQuery,
    MyTicketsQueryVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<MyTicketsQuery, MyTicketsQueryVariables>(
    MyTicketsDocument,
    options,
  );
}
export function useMyTicketsSuspenseQuery(
  baseOptions?: Apollo.SuspenseQueryHookOptions<
    MyTicketsQuery,
    MyTicketsQueryVariables
  >,
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useSuspenseQuery<MyTicketsQuery, MyTicketsQueryVariables>(
    MyTicketsDocument,
    options,
  );
}
export type MyTicketsQueryHookResult = ReturnType<typeof useMyTicketsQuery>;
export type MyTicketsLazyQueryHookResult = ReturnType<
  typeof useMyTicketsLazyQuery
>;
export type MyTicketsSuspenseQueryHookResult = ReturnType<
  typeof useMyTicketsSuspenseQuery
>;
export type MyTicketsQueryResult = Apollo.QueryResult<
  MyTicketsQuery,
  MyTicketsQueryVariables
>;
