query myEvent(
  $input: PaginatedInputEventsSearchInput!
  $userTicketSearchInput: EventsTicketsSearchInput
) {
  searchEvents(input: $input) {
    data {
      id
      name
      description
      startDateTime
      endDateTime
      address
      publicShareURL
      previewImage {
        url
      }
      bannerImage {
        url
      }
      mobileBannerImage {
        url
      }
      community {
        id
        name
      }
      status
      usersTickets(input: $userTicketSearchInput) {
        id
        approvalStatus
        paymentStatus
        redemptionStatus
        createdAt
        publicId
        ticketTemplate {
          id
          name
          description
        }
      }
    }
    pagination {
      currentPage
      pageSize
      totalPages
      totalRecords
    }
  }
}
