import { Nav } from "@/components/nav";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import classNames from "classnames";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["500", "700", "900"],
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="es" className="h-screen overflow-hidden bg-slate-950">
        <body
          className={classNames(
            inter.variable,
            roboto.variable,
            "h-full overflow-hidden",
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Nav />
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
