import { Nav } from "@/components/nav";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import classNames from "classnames";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["500", "700", "900"],
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className="h-screen overflow-hidden bg-slate-950">
      <body
        className={classNames(
          inter.variable,
          roboto.variable,
          "h-full overflow-hidden text-white"
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
