query getEventAndTickets($id: String!, $coupon: String) {
  event(id: $id) {
    id
    name
    address
    description
    startDateTime
    endDateTime
    status
    logoImage {
      url
    }
    bannerImage {
      url
    }
    mobileBannerImage {
      url
    }
    community {
      name
    }
    users {
      id
      name
    }
    tickets(input: { coupon: $coupon }) {
      ...EventTicketFragment
    }
  }
}
