query getEventAndTickets($input: String!) {
  event(id: $input) {
    id
    name
    address
    description
    startDateTime
    endDateTime
    status
    logoImage {
      url
    }
    bannerImage {
      url
    }
    mobileBannerImage {
      url
    }
    community {
      name
    }
    users {
      id
      name
    }
    tickets {
      ...EventTicketFragment
    }
  }
}
