mutation CheckPurchaseOrderStatus($input: CheckForPurchaseOrderInput!) {
  checkPurchaseOrderStatus(input: $input) {
    id
    paymentLink
    status
    finalPrice
    paymentPlatform
    createdAt
    publicId
    currency {
      id
      currency
    }
    tickets {
      id
      approvalStatus
      paymentStatus
      redemptionStatus
      publicId
      ticketTemplate {
        id
        name
        description
        isFree
        event {
          id
          name
          address
          description
          startDateTime
          endDateTime
          status
          publicShareURL
          logoImage {
            url
          }
          community {
            name
          }
        }
        prices {
          id
          amount
          currency {
            currency
            id
          }
        }
      }
    }
  }
}
