query myProfile {
  me {
    id
    bio
    lastName
    username
    imageUrl
    isSuperAdmin
    email
    name
    impersonatedUser {
      id
      name
    }
    communities {
      id
      name
    }
  }
}
