mutation CheckPurchaseOrderStatus($input: CheckForPurchaseOrderInput!) {
  checkPurchaseOrderStatus(input: $input) {
    status
    tickets {
      approvalStatus
      paymentStatus
      redemptionStatus
    }
  }
}
