query myEvents(
  $input: PaginatedInputEventsSearchInput!
  $userTicketSearchInput: EventsTicketsSearchInput
) {
  searchEvents(input: $input) {
    data {
      id
      name
      description
      startDateTime
      address
      bannerImageSanityRef
      community {
        id
        name
      }
      status
      usersTickets(input: $userTicketSearchInput) {
        id
        approvalStatus
        paymentStatus
        redemptionStatus
        ticketTemplate {
          description
          id
        }
      }
    }
    pagination {
      currentPage
      pageSize
      totalPages
      totalRecords
    }
  }
}
